### ISSUE TITLE
Frequent test failure in paintTheGridOnClick test

### ISSUE THREAD

**Issue by JaroslavTulach** [jtulach/bck2brwsr#8]
There is a random test failure on Mac when running on top of GraalVM:
```
org.apidesign.bck2brwsr.vmtest.impl.Bck2BrwsrCase.paintTheGridOnClick[fxbrwsr] (from org.apidesign.bck2brwsr.kofx.KnockoutFXTest)
Failing for the past 2 builds (Since Unstable#37 )
Took 10 sec.
Error Message

timeout(101)

Stacktrace

java.lang.InterruptedException: timeout(101)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apidesign.bck2brwsr.vmtest.impl.Bck2BrwsrCase.executeCode(Bck2BrwsrCase.java:102)

Standard Error

May 16, 2018 5:54:37 AM org.apidesign.bck2brwsr.launcher.BaseHTTPLauncher$1 service
INFO: Request for 11 case. Sending net.java.html.json.tests.MinesTest.paintTheGridOnClick
May 16, 2018 5:54:48 AM org.apidesign.bck2brwsr.launcher.BaseHTTPLauncher$1 service
INFO: Received result for case 11 = java.lang.InterruptedException:timeout(101)
```
consider making the test more stable.

**Comment by jtulach** [comment]
No longer the case, as far as I can say.
